name: datamine_client
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  extension_google_sign_in_as_googleapis_auth: ^2.0.7
  flutter: {sdk: flutter}
  google_sign_in: ^5.4.2
  googleapis: ^9.2.0
  hash: ^1.0.4
  isar: 3.0.5
  isar_flutter_libs: 3.0.5
  logging: ^1.1.1
  package_info_plus: ^3.0.3
  path: ^1.8.2
  path_provider: ^2.0.13

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test: {sdk: flutter}
  google_sign_in_platform_interface: ^2.2.0
  isar_generator: 3.0.5
  mockito: ^5.3.2
