name: datamine_client
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  async: ^2.11.0
  background_fetch: ^1.2.1
  device_info_plus: ^9.1.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.7
  flutter: {sdk: flutter}
  google_sign_in: ^6.1.6
  googleapis: ^11.4.0
  hash: ^1.0.4
  http: ^1.1.0
  logging: ^1.1.1
  package_info_plus: ^4.2.0
  path: ^1.8.2
  path_provider: ^2.0.13
  shared_preferences: ^2.1.1
  uuid: ^4.1.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^3.0.1
  flutter_test: {sdk: flutter}
  google_sign_in_platform_interface: ^2.2.0
  mockito: ^5.3.2
